# Generated by Django 6.0.2 on 2026-03-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('serial', 'Asesino serial'), ('homicide', 'Homicidio'), ('missing', 'Persona desaparecida'), ('fraud', 'Fraude'), ('other', 'Otro')], default='other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='event_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
