# Generated by Django 6.0.2 on 2026-03-16 02:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_case_type_case_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
